Improve Debian/Ubuntu install instructions
aiven/myhoard pull request #106
Opened 2022-11-30 10:33 UTC by jelmer

Drive-by fix to instructions to allow running MyHoard on Debian/Ubuntu:

* Don't run scripts with sudo - they already call sudo when necessary
* When running on sid/testing (for which no packages are published), install stable packages
* Drop 'RUN' prefix which was presumably copied from a Dockerfile
* Allow overriding VERSION_ID
* Factor out 'make build-dep-ubuntu', for consistency with Fedora

2022-11-30 22:17 UTC, jelmer commented
> I'm OK with all the ubuntu-related changes. Do we want/need the debian branch? We don't have a way to test it automatically.

I've tested it locally since I mostly use Debian. It's unlikely to regress (especially for people not on Debian anyway), but happy to drop that if you prefer.

2022-12-02 18:30 UTC, aris-aiven commented
I think it's reasonable to say we can change according to user feedback if Debian behaviour changes in the future.

2022-12-07 08:05 UTC, kmichel-aiven requested changes

2022-12-07 12:09 UTC, jelmer commented on README.md
> +PERCONA_VERSION=8.0.29-22-1.bullseye
Thanks, didn't realize that. Updated & also added a note below.

2022-12-08 09:13 UTC, kmichel-aiven approved these changes

2022-12-08 09:13 UTC, merged