consider new configuration "backup_disabled_until"
aiven/myhoard pull request #136
Opened 2023-02-03 13:50 UTC by kathia-barahona

test periodic backups

# About this change: What it does, why it matters

2023-02-06 15:46 UTC, kathia-barahona commented on requirements.dev.txt
> +time-machine
**comment** using this module just for mocking time and test default intervals.

2023-02-07 18:04 UTC, alanfranz requested changes, later dismissed
I don't understand how the ```backup_disabled_until``` value should be configured. We're disabling backups for X minutes... from when? From when the option is set? But then, we never unset this. If I find this config set, when should I expect the new backup to happen?

I think the "backup_disabled_until" should be a full timestamp (I'm not sure what format we're using elsewhere, take a look around). If the current time when trying to take a backup is before that, just skip that backup.

2023-02-08 09:09 UTC, kathia-barahona commented
> I don't understand how the `backup_disabled_until` value should be configured. We're disabling backups for X minutes... from when? From when the option is set? But then, we never unset this. If I find this config set, when should I expect the new backup to happen?
> 
> I think the "backup_disabled_until" should be a full timestamp (I'm not sure what format we're using elsewhere, take a look around). If the current time when trying to take a backup is before that, just skip that backup.

Yes I see your point, tho I thought the functionality was more about increasing the time interval between backups, because currently is at least `backup_interval_minutes / 2`.  Maybe I got confused when talking with @alexole. @alexole is it better to just change it with a timestamp?

2023-02-08 09:16 UTC, alanfranz commented
You can implement it as you see fit, but we need to keep the naming clean. If you just want to be able to override the backup_interval... you could call this option ```backup_interval_override_seconds```. And: please make sure such override is actually respected (we had a bug with backup_interval that made it impossible to span more than 24h) & validated.

2023-02-14 17:31 UTC, alanfranz commented
@kathia-barahona remember to re-add Team Bruteforce (and or team OSS in this case) as reviewers, otherwise you can get stuck at waiting for a single person (me, in this scenario :-) )

2023-02-16 12:39 UTC, alanfranz commented
I'm not sure I understand the change, but the backup logic in myhoard was pretty complex. If anybody wants to chime in in place of me, please do so; otherwise I'll take another look in the next days.

2023-02-16 12:50 UTC, rikonen commented
Pull request descriptions talks about feature that this pr no longer implements and first commit has code that is deleted in the second commit. Should squash commits and update commit and pr description to match what this actually does, now this pr looks quite confusing.

2023-02-17 14:42 UTC, kathia-barahona commented
> Pull request descriptions talks about feature that this pr no longer implements and first commit has code that is deleted in the second commit. Should squash commits and update commit and pr description to match what this actually does, now this pr looks quite confusing.

oops, you are right. will update this

2023-03-02 08:46 UTC, Ormod commented
The change is in conflict with master.

2023-03-03 07:46 UTC, kmichel-aiven approved these changes

2023-03-03 07:47 UTC, merged